version: "3.2"

services:
  finance-summary-api:
    image: finance-summary-api
    build:
      context: FinancialSummaryApi/
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    environment:
      - DynamoDb_LocalMode=true
      - DynamoDb_LocalServiceUrl=http://dynamodb-database:8000
      - AWS_REGION=eu-west-2
      - AWS_ACCESS_KEY_ID=fco1i2
      - AWS_SECRET_ACCESS_KEY=8kmm3g
    links:
      - dev-database
  dev-database:
    env_file:
      - database.env
    image: postgres:12
    volumes:
      - ./database:/docker-entrypoint-initdb.d

  finance-summary-api-test:
    image: finance-summary-api-test
    build:
      context: .
      dockerfile: FinancialSummaryApi.Tests/Dockerfile
    environment:
      - DynamoDb_LocalMode=true
      - DynamoDb_LocalServiceUrl=http://dynamodb-database:8000
      - AWS_REGION=eu-west-2
      - AWS_ACCESS_KEY_ID=fco1i2
      - AWS_SECRET_ACCESS_KEY=8kmm3g
    links:
      - dynamodb-database

  dynamodb-database:
    image: amazon/dynamodb-local
    ports:
      - 8000:8000
